### ISSUE TITLE
Inicio y creación de usuarios

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/backend-aiding#1]
Se debe crear la capa de lógica que interactúe con las vistas de creación de login de usuario administrador y creación de usuario.
Un usuario tiene los siguientes campos, además de su enumerado Role. El usuario administrador tiene permisos para poder crear otros usuarios. La parte izquierda de las notificaciones no es necesaria de momento. Simplemente la lógica necesaria para que un usuario administrador pueda iniciar sesión y tenga permisos para crear nuevos usuarios con los atributos mostrados en el modelo y teniendo en cuenta los próximos requisitos.

![Image](https://user-images.githubusercontent.com/57068405/222419074-9a816fde-be00-4057-8efa-9055dd4e488b.png)

<html>
<body>

ID | Prioridad | Titulo | Descripción
-- | -- | -- | --
RF-01 | Primario | Gestión de miembros. | El sistema deberá permitir al administrador listar, crear, editar, dar de baja/alta a miembros de la base de datos.
RSE-01 | Primario | Nivel de seguridad alto. | El sistema deberá implementar medidas de autenticación y autorización sólidas, así como diferentes mecanismos de seguridad.
RU-01 | Primario | Facilidad de usabilidad. | El sistema deberá ser seguro, accesible e intuitivo.

</body>
</html>

**Comment by rosmolarr** [comment]
El backend esta bien, solo habria que conectarlo con el frontend que tiene asignado @Josdelsan.

**Comment by rosmolarr** [comment]
@rubsuadav te asigno a ti para que ayudes a fire a conectarlo.

**Comment by Josdelsan** [comment]
Cuando se registra no inicia sesión automáticamente, te redirige al login y hay que iniciar. Se ha hecho así porque habia que anidar 3 promesas y empezó a dar fallo. Para no echarla 5 horas a la tarea basicamente.
