### ISSUE TITLE
Mapa de recursos

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/backend-aiding#10]
Tarea frontend: ISPP-2023-NGO-P3/frontend-aiding#12

Realizar un mapa interactivo donde se muestren puntos de interés que el usuario administrador puede insertar. **Valorar** OpenStreetMap como alternativa open-source a Google Maps. Haciendo consultas quizas a partir de la ciudad y la calle podemos ahorrarnos tener que meter coordenadas. Incluso puede que pulsando en el mapa nos devuelva las coordenadas y la calle.

<html>
<body>

ID | Prioridad | Título | Descripción
-- | -- | -- | --
RF-14 | Primario | Gestionar recursos (mapa). | El sistema debe permitir crear recursos con puntos de interés, los editen, los listen y los eliminen.
RI-05 | Primario | Recursos (Mapa). | El sistema debe almacenar información de los recursos con: titulo, descripción, calle, numero, ciudad, comentarios adicionales, coordenadas x e y.

</body>
</html>

**Comment by mansanrod4** [comment]
Hay que añadir los atributos tipo de recurso (asociacion vecinos, asociacion mayores, residencia, etc) y tlf de contacto al modelo Recurso.
