### ISSUE TITLE
Registro de voluntarios backend

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/backend-aiding#25]
Se pide realizar CRUD del módulo voluntarios. En esta tarea no se realizarán los turnos.

![Image](https://user-images.githubusercontent.com/80246352/225655409-da824e56-f97a-4963-9e1f-01f748a285aa.png)

Además de esos atributos se pide añadir un enumerado llamado conocimientos, para poder administrar estos datos con mayor facilidad. Este enumerado constará de conocimientos sobre:
- informática
- manejar un camión
- gestionar almacén

Actualmente vamos a tomar como si los voluntarios no pudieran loguearse al tratarse de una tarea más compleja.

<html>
<body>

ID | Prioridad | Titulo | Descripción
-- | -- | -- | --
RI-08 | Primario | Voluntarios. | El sistema debe registrar de cada voluntario: número de voluntario, nombre y apellidos, situación (a la espera, en trámite y los demás lo tienen que definir), NIF, código postal, fecha de nacimiento, teléfono, email, sabe de informática, sabe de manejar un camión, sabe gestionar almacén y otros conocimientos, si está activo y el rol (voluntario de recogida, capitán y supervisor). Además, dispondrá de otro campo llamado observaciones para dejar comentado lo que sea necesario.

</body>
</html>

**Comment by lNoelia** [comment]
Falta por añadir algunos estados a situación, código postal al modelo y solucionar el validador de nif

**Comment by Rick3600** [comment]
Añadidos estados, código postal y arreglado problemas con validador
