### ISSUE TITLE
Asignación de roles a usuario - backend

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/backend-aiding#26]
poder asignar los roles a los usuarios ( capitan etc etc) con sus debidos permisos

**Comment by rubsuadav** [comment]
Analizando mi tarea me he dado cuenta que, pues perteneciendo al módulo de voluntarios, al proceder a realizarla para crear los roles de capitan, supervisor, et, a los diferentes "voluntarios" ya existiía un desplegable con dichos roles (tal y como se puede ver en la foto de abajo).


![Image](https://user-images.githubusercontent.com/80253875/229280411-c8554432-651d-4ea4-ba18-c5b98df6184c.png)

Tras analizarlo, procedí a comprobar su funcionamiento y era el correcto ya que en el frontend se puede asignar el rol a dicho voluntario tal y como se adjunta en la siguiente foto de abajo.


![Image](https://user-images.githubusercontent.com/80253875/229280642-58a29f30-14d5-4d52-b4c0-a247ca68db98.png)


Dichas pruebas las he realizado estando en mis correspondientes ramas estando con la última versión de la rama develop

Por lo que, procedo a hacer una pregunta debido a que no me queda muy claro la tarea entonces. ¿Debo de hacer lo de los roles en los "usuarios" del módulo base?
Espero una posible respuesta porque estoy un poco rallado al ver que en el módulo que debo de realizar la tarea me la encuentro hecha. @lNoelia @rosmolarr @Manueldm01

**Comment by rosmolarr** [comment]
Si, eso que pones son "tipos de voluntarios". Tu tarea era asignar roles a los **usuarios** del sistema. Estos roles serían:

- Un usuario normal, que pueda ver la aplicación y en un futuro, apuntarse a los eventos.
- Un usuario tipo capitán o supervisor, que también vea la aplicación normal pero tenga el panel de administrador de turnos y voluntarios, ya que ellos son los que organizan los turnos con sus voluntarios.
- Un usuario administrador que tenga acceso a todo.

**Comment by rubsuadav** [comment]
Estado de la tarea, ya se ha implementado la lógica de los roles a usuarios en el backend pudiendo comprobar que siendo un rol capitan y supervisor tiene acceso a los CRUDs de turnos y voluntarios

 
<img width="255" alt="image" src="https://user-images.githubusercontent.com/80253875/229353154-e85335b7-76c1-41aa-a6e2-11b67b4195de.png">
En esa foto se pueden ver los 2 roles extras (a parte del de admin que lo gestiona sólo django) 

<img width="503" alt="image" src="https://user-images.githubusercontent.com/80253875/229353208-c741a636-898d-4aed-974b-171868228152.png">

Aquí se pueden ver los permisos que existen ahora (se pueden ver los CRUDs), para que funcione debe de haber otra tabla intermedia (puesto que esa relación por defetco de django es MtM) que me relacionen permisos y roles, dicha tabla es esta de abajo:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/80253875/229353297-9d5f0abd-aa7d-47bb-a2eb-bbe2eec8103f.png">

La columna "group_id" hace referencia al id de la primera tabla y la columna "permission_id" hace referencia al id de la segunda tabla, puede verse por tanto que los IDs de los permisos que tienen esos 2 roles es la correcta probándose pues la tarea de manera correcta en el backend, además está lista también para ser procesada por el frontend metiendo en el views.py de los 2 CRUDs su decorador pertinente como puede verse en la foto de abajo.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/80253875/229353451-c1fa376f-9dcb-4875-a1a3-a753aaf35f48.png">

Dicho decorador detrás del "IsAdminUser" me indica si dicho rol tiene un permiso referente a la segunda tabla de la BBDD
