### ISSUE TITLE
Importación de socios

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/backend-aiding#3]
Para esta tarea hay que recoperar el .csv enviado desde el front y persistir los datos recuperados del mismo en la base de datos.
En el canal de bosco por discord si no me equivoco hay un fichero de muestra de los campos de los csv que son necesarios, el orden etc.

**Comment by rosmolarr** [comment]
Se vuelve a abrir para añadir mejoras a la tarea

**Comment by Manueldm01** [comment]
Me encuentro atascado en esta tarea debido a que no encuentro la forma de hacer que solo los administradores puedan realizar la importación, sin esto no puedo continuar.

**Comment by rosmolarr** [comment]
Con que no puedan acceder valdría, si no estas logueado y pones la url directamente te deja importar? Es que por lo que he visto como es algo de la vista de socios y que ahi se abre el panel, siempre que no puedan acceder a socios estaría bien no?, por otro lado, lo de la importación del archivo exacto que nos mandarón que puse de comentario en la issue, esta hecho?

**Comment by Manueldm01** [comment]
Lo de los permisos está solucionado, es obligatorio loguearse y además está en la pestaña del admin, luego lo del archivo exacto es justo lo que he hecho, ahora se crea también la donación asociada al socio.
