### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/backend-aiding#35]
@celhersot: Realiza los test del módulo de voluntarios .
@Manueldm01: Realiza los test del módulo de socios.

**Comment by rubsuadav** [comment]
Para una mejor organización de los tests creo que lo recomendable es que cada uno se encarge del módulo correspondiente, en mi caso el de "information"

**Comment by rubsuadav** [comment]
Se ha implementando el test CRUD unitario correspondiente a las secciones probando cada ramificación de los status asociado, además también se ha avanzado el test unitario CRUD de las noticias llegando a hacer sólo todas las posibles opciones del GET e intentado el POST positivo pero no pudiéndolo rematar

**Comment by rubsuadav** [comment]
Se ha implementando el test CRUD unitario correspondiente al 90% del módulo information quedando el testeo del endpoint customizado de mostrar los anuncios cuya seccion es X y la parte de los recursos

**Comment by Manueldm01** [comment]
Se han implementado los test de los socios sin mayores inconvenientes, pero a la hora de hacer los test de las donaciones me he encontrado problemas, ya que en vez de usar Response usa JsonResponse y es mucho más confuso probarlo.

**Comment by celhersot** [comment]
Se ha implementado el test CRUD unitario correspondiente a los voluntarios, testeando también el validador del DNI.

**Comment by lNoelia** [comment]
Para Noelia:  test del stock

**Comment by rosmolarr** [comment]
Estoy teniendo problemas con los tests de turnos, ya que todos dan error 301, no se si es problema mio o de la persona que hizo turnos en primer lugar. Seguiré investigando.

**Comment by rosmolarr** [comment]
He terminado los tests de turno y funcionan todos, pero me he dado cuenta de que hay 4 tests de voluntarios que dan error, la persona que tuviera esa tarea tiene que arreglarlos, en concreto son:

- test_update_positive_volunteer_status_OK (volunteers.tests.VolunteerTests)
- test_update_negative_volunteer_status_CONFLICT (volunteers.tests.VolunteerTests)
- test_create_positive_volunteer_status_CREATED (volunteers.tests.VolunteerTests)
- test_create_negative_volunteer_status_CONFLICT (volunteers.tests.VolunteerTests)

Los 4 son errores del postal code: line 55, _**in post state=jd['state'],situation=jd['situation'],rol=jd['rol'],postal_code=jd['postal_code'], KeyError: 'postal_code'**_

**Comment by lNoelia** [comment]
Se debe actualizar la tarea con los contenidos adquiridos en la píldora teórica de esta semana.

**Comment by lNoelia** [comment]
Para Juanjo , Nico y Manu S :  Hacer test exploratorio (dividir la aplicación en 3 partes y probar intentando buscar fallos en restricciones, accesos no permitidos etc etc siguiendo la teoría) 

Para Manu D, Marcos y cualquier persona que tenga tiempo esta semana : Hacer test de integración entre los módulos ( seguir una historia de usuario y realizarla por completo)

**Comment by nicsanmen** [comment]
Juanjo, Manu S y yo nos divimos ayer la aplicación para hacer los test exploratorios. Antes de saber que no importaba tenerlo para el martes la idea era tenerlo hecho para esta noche, así que lo tendremos cuanto antes

**Comment by celhersot** [comment]
Corregidos los tests de voluntarios.

**Comment by Manueldm01** [comment]
Test de Donation y Communication hechos y añadidos algunos test de integración
