### ISSUE TITLE
Gestión de socios

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/backend-aiding#4]
Tarea frontend: ISPP-2023-NGO-P3/frontend-aiding#5

Un socio tiene los siguientes atributos y relaciones. 

![Image](https://user-images.githubusercontent.com/80246352/223172145-46352bbd-a3b5-43d4-887a-eff258c4ff1a.png)

Se pide realizar CRU de los socios (el borrado no), y sus comunicaciones siguiendo los siguientes requisitos

<html>
<body>

ID | Prioridad | Título | Descripción
-- | -- | -- | --
RF-01 | Primario | Socios. | El sistema debe almacenar los siguientes datos de cada socio: nombre, apellido, dni, teléfono, correo electrónico, provincia, IBAN, si está dado de alta o no, la periodicidad de sus donaciones y la cantidad que dona. 
RI-04 | Primario | Comunicaciones. | El sistema debe almacenar la siguiente información de cada comunicación: fecha, tipo, socio y descripción. 

</body>
</html>

**Comment by rosmolarr** [comment]
Acabo de darme cuenta de que el modelo esta mal realizado. Se han olvidado de añadir todos estos datos que también tiene un socio.
![image](https://user-images.githubusercontent.com/80246352/223111923-ba4ea46c-957d-40b0-a16f-ac849b8c803e.png)
Hay que revisar que datos faltarían y añadirlos. Además también hay que cambiar lo siguiente:

![image](https://user-images.githubusercontent.com/80246352/223112072-71484063-50f0-46b5-b6a8-c6f5e4ca03c8.png)

Los estados hay que ponerlos en español para que se vea bien en la página.

![image](https://user-images.githubusercontent.com/80246352/223112174-316fc222-2dd8-4e11-97e6-73d7593fdd7d.png)

Las urls hay que ponerlas sin el partners delante, ya que de por si django pone /clase/ delante de las urls.

**Comment by rosmolarr** [comment]
Se deja la issue abierta a la espera de la contestación de don bosco para terminar de añadir los ultimos atributos.
