### ISSUE TITLE
Registro de turnos- backend

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/backend-aiding#47]
Se debe crear "turnos" con los campos: "fecha, hora de comienzo y hora de fin".

Esta tarea tiene de límite de entrega el sábado 25/03 8.00 am

**Comment by juaalvcam** [comment]
El codigo esta terminado, pero me falta algun error por solucionar

**Comment by juaalvcam** [comment]
Listo a la espera de revisión
