### ISSUE TITLE
Notificaciones a voluntarios

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/backend-aiding#58]
Permitir las notificaciones a varios voluntarios y que notifique automáticamente cuando te añaden un turno (cuando pasa de modo draft a publicado)
**Fecha limite: Sábado 15 a las 12:00**

**Comment by nicsanmen** [comment]
Ya está hecha la PR. Cuando se asigna un voluntario a un turno, se le envía automaticamente un correo a este. 
He estado también viendo con Fire el tema de notificaciones a voluntarios/socios "en grupo" y parece que es todo cosa del front, por eso subo esto para que se vaya viendo
