### ISSUE TITLE
Turnos y voluntarios

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/backend-aiding#60]
Se debe añadir a la entidad turnos un atributo sobre con el id del supervisor que lo haya creado, un título que pueda diferenciar un turno de otro y un atributo booleano que sirva para distinguir si un turno es un borrador o una versión definitiva.
**Fecha limite: Sábado 15 a las 12:00**

**Comment by cardelbec** [comment]
Daily: la tarea avanza bien, ya he añadido los atributos necesarios y un par de llamadas de la API que me hacían falta en el frontend. Solo me falta gestionar los permisos para que solo se puedan utilizar como supervisor/capitán y un par de retoques en algunas de las llamadas de la API.
