### ISSUE TITLE
Apuntarse a evento

### ISSUE THREAD

**Issue by lNoelia** [ISPP-2023-NGO-P3/backend-aiding#61]
Permitir a los usuarios apuntarse a los eventos con su nombre y telefono ( poner también el número de cupos que ya están cubiertos por ejemplo 3/5 ) y señalar como completo cuando ya se hayan apuntado todas las personas (ya no quedan plazas))
**Fecha limite: Sábado 15 a las 12:00**

**Comment by juaalvcam** [comment]
He completado gran parte de la tarea aunque no me pasa todavía las pruebas con Postman

**Comment by juaalvcam** [comment]
Progreso completado, salvo probar una validación con Postman
