### ISSUE TITLE
Cálculo total donaciones - backend

### ISSUE THREAD

**Issue by lNoelia** [ISPP-2023-NGO-P3/backend-aiding#62]

**Comment by aisqazcev** [comment]
A total_donation se le debe pasar una fecha fin, con la que realizar el cálculo, ya que tomará la fecha de creación y esta fecha fin para calcular el número de periodos por los que multiplicar la cantidad. 
La relación que existe ahora entre partners y donation, es de una a muchas, y solo será posible crear una donación por año, siendo modificable cantidad y periodicidad en caso de error al crearla.

**Comment by aisqazcev** [comment]
total_donation ahora tiene como fecha fin: el año en el que se ha creado, diciembre y día 10.
