### ISSUE TITLE
Generación de certificados

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/backend-aiding#8]
Usando word y pdf, con la pantilla mandada por bosco, realizar una generación de pdf con los datos de los socios y la documentación.

<html>
<body>

ID | Prioridad | Titulo | Descripción
-- | -- | -- | --
RF-08 | Primario | Generar certificado para cada socio. | El sistema debe permitir generar un certificado para cada socio que justifique el número de donaciones que hace al año.
RI-03 | Primario | Certificados. | El sistema debe generar certificados con los siguientes campos: nombre, apellido, DNI, provincia y nº de donaciones al año.
RN-03 | Primario | Certificados no modificables. | El sistema no permitirá editar los certificados generados.

</body>
</html>

**Comment by rosmolarr** [comment]
No hizo falta el backend para la generación de certificados
