### ISSUE TITLE
Creación de noticias

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/backend-aiding#9]
Tarea backend: ISPP-2023-NGO-P3/frontend-aiding#10

Realizar secciones donde un usuario no logeado pueda consultar noticias que sean redactadas o ya bien enlaces a noticias web. Los administradores podrán añadir noticias y seleccionar en que sección quieren que aparezcan. Habrá que valorar como implementar ese dinamismo en las secciones (dropdown menu en navbar?). También hay que definir bien que formato y distribución van a tener las noticias normales (número de fotos, párrafos, títulos, ¿autor?). 

<html>
<body>

ID | Prioridad | Título | Descripción
-- | -- | -- | --
RF-13 | Primario | Tablón de anuncios. | El sistema debe proveer un tablón de anuncios donde el administrador podrá crear, editar, listar y eliminar el contenido de diferentes secciones: “Anuncios” y “Recursos”. 
RI-06 | Primario | Anuncio. | El sistema debe almacenar información de los anuncios con: titulo, descripción, url, archivo multimedia, sección. 
RI-07 | Primario | Sección. | El sistema debe almacenar información de las seccione con: nombre  

</body>
</html>

**Comment by Josdelsan** [comment]
Revisando el commit f201c6b voy a comentar las cosas que he visto:

- Hace falta meter la lógica de que las noticias solo la pueden crear usuarios admins (hay unos decoradores que lo gestionan solo en django) permission_required(https://docs.djangoproject.com/en/4.1/topics/auth/default/)
- Los token csrf puede ser peligroso haberlo desactivado, debe haber una alternativa para dejarlo puesto y que funcione los post y put
- La comprobación de los objetos que llegan, ¿no hace falta hacer ninguna comprobación antes de intentar guardar el objeto? Puede generar fallos
- Como gestionas los objetos que devuelves, esta bien hacerlo sin el rest framework? sin serializar puede que la api no cumpla los estándares rest?

Adicionalmente, igual tendría sentido poder poner en modo borrador "draft" las noticias antes de publicarlas e incluso ver una previsualización. 
Afecta a https://github.com/ISPP-2023-NGO-P3/frontend-aiding/issues/10 @lNoelia

**Comment by rubsuadav** [comment]
Perfecto, he entendido tu feedback y mañana lo antes posible me pongo a retocar mi tarea cumpliendo con lo que me has comentado.
Con respecto al punto 3, no entiendo a lo que te refieres exactamente
Con respecto al punto 4, no le he metido rest-framework porque implicaba crear serializers y es mas complejo de entender y la verdad es que no me  gusta marear a la gente con tantas cosas, desde el punto de vista de los estándares rest no se si se deja de cumplir o no dichos estándares, el video de la API con django que me vi lo hacía así sin usar rest-framework, ¿debería de hacerlo con rest-framework?.

**Comment by Josdelsan** [comment]
Si no surjen problema por no usar RestFramework lo dejamos así de momento para agilizar el desarrollo. Ya lo cambiaremos si hiciera falta.

El punto 3 me refiero a la comprobación de tipos, restricciones, etc. Por ejemplo que los archivos multimedia que se suban sean png, gif, mp4, etc y no te puedan colar un xml o pdf. Eso en principio se hace en el Frontend pero es buena práctica comprobarlo en el Backend porque te pueden hacer la petición a mano. No sé si hay por ejemplo un límite de caracteres para las noticias o título. Ese tipo de comprobaciones que haciamos en dp2

**Comment by rubsuadav** [comment]
Vale perfecto, ya estoy en ello, cuando lo realice vuelvo a subir los cambios a remoto para que @lNoelia y tu reviséis los cambios y verifiquéis la correcta implementación. Cuando lo suba os avisaré para que lo podáis chequear.

**Comment by Josdelsan** [comment]
Vamos a darle una vuelta a como se guarda la noticia. Por simplificar vamos a dejar una única imagen y guardar la noticias en formato html o json para poder crearla usando un editor de texto rico. Queda concretar con el frontend como se hará.

**Comment by Josdelsan** [comment]
Se ha adaptado el backend a las nuevas necesidades del frontend (formularios multipart-form/data), ya que hay formularios que mandan imágenes y inputs de texto.

De momento no se usa multimedia nada mas que la propia imagen de la cabecera que esta en el modelo de la noticia. Habria que plantear si añadirlo.

Plantear también añadir un modo borrador y darle utilidad al estado de las secciones, de momento no está implementado.
